apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aggregator
  name: aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator
  strategy: {}
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
      - name: aggregator
        image: localhost:5000/aggregator:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: rest-port
---
apiVersion: v1
kind: Service
metadata:
  name: aggregator
  labels:
    app: aggregator
spec:
  type: NodePort
  selector:
    app: aggregator
  ports:
  - name: rest
    port: 80
    targetPort: rest-port
    nodePort: 30103
