apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: pact-postgres
  name: pact-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      run: pact-postgres
  template:
    metadata:
      labels:
        run: pact-postgres
    spec:
      containers:
      - image: postgres:9.5
        name: pact-postgres
        env:
        - name: POSTGRES_PASSWORD
          value: "pactbroker"
        - name: POSTGRES_USER
          value: "pactbroker"
        - name: POSTGRES_DB
          value: "pact"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: pact-postgres-service
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 32752
  selector:
    run: pact-postgres
