apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: world-pop
  name: world-pop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world-pop
  strategy: {}
  template:
    metadata:
      labels:
        app: world-pop
    spec:
      containers:
      - image: localhost:5000/world-pop:3.0.0
        name: world-pop
        ports:
        - containerPort: 8080
          name: rest-port
---
apiVersion: v1
kind: Service
metadata:
  name: world-pop
  labels:
    app: world-pop
spec:
  type: NodePort
  selector:
    app: world-pop
  ports:
  - name: rest
    port: 80
    targetPort: rest-port
    nodePort: 30101
